function New-CodexDesktopResult {
  param(
    [bool]$Found = $false,
    [string]$Source = "none",
    [string]$ExecutablePath = "",
    [string]$AppId = "",
    [string]$PackageFullName = "",
    [string]$InstallLocation = "",
    [string]$ErrorMessage = ""
  )

  [PSCustomObject]@{
    Found = $Found
    Source = $Source
    ExecutablePath = $ExecutablePath
    AppId = $AppId
    PackageFullName = $PackageFullName
    InstallLocation = $InstallLocation
    Error = $ErrorMessage
  }
}

function Get-CodexDesktopProcess {
  try {
    $processes = Get-CimInstance Win32_Process -Filter "Name = 'Codex.exe'" -ErrorAction Stop
  } catch {
    return $null
  }

  $desktopProcesses = @($processes | Where-Object {
    -not [string]::IsNullOrWhiteSpace($_.ExecutablePath) -and
    (Split-Path -Leaf $_.ExecutablePath) -ieq "Codex.exe" -and
    $_.ExecutablePath -notmatch '\\resources\\codex\.exe$' -and
    $_.CommandLine -notmatch '\s--type='
  })

  if ($desktopProcesses.Count -gt 0) {
    return $desktopProcesses | Select-Object -First 1
  }

  return @($processes | Where-Object {
    -not [string]::IsNullOrWhiteSpace($_.ExecutablePath) -and
    (Split-Path -Leaf $_.ExecutablePath) -ieq "Codex.exe" -and
    $_.ExecutablePath -notmatch '\\resources\\codex\.exe$'
  } | Select-Object -First 1)
}

function Test-CodexDesktopRunning {
  return [bool](Get-CodexDesktopProcess)
}

function Get-CodexStartApp {
  try {
    $apps = @(Get-StartApps -ErrorAction Stop | Where-Object {
      ($_.Name -eq "Codex" -or $_.AppID -like "OpenAI.Codex*") -and
      $_.AppID -notlike "Microsoft.AutoGenerated.*"
    })
    if ($apps.Count -gt 0) {
      return $apps | Select-Object -First 1
    }
  } catch {
    return $null
  }
  return $null
}

function Resolve-CodexDesktopApp {
  param(
    [string]$CodexAppPath = "",
    [string]$CodexAppId = ""
  )

  if (-not [string]::IsNullOrWhiteSpace($CodexAppPath)) {
    $fullPath = [System.IO.Path]::GetFullPath($CodexAppPath)
    if (Test-Path -LiteralPath $fullPath) {
      return New-CodexDesktopResult -Found $true -Source "explicit-path" -ExecutablePath $fullPath
    }
    return New-CodexDesktopResult -Source "explicit-path" -ErrorMessage "Codex app path was not found: $fullPath"
  }

  if (-not [string]::IsNullOrWhiteSpace($CodexAppId)) {
    return New-CodexDesktopResult -Found $true -Source "explicit-appid" -AppId $CodexAppId
  }

  $running = Get-CodexDesktopProcess
  if ($running -and -not [string]::IsNullOrWhiteSpace($running.ExecutablePath)) {
    return New-CodexDesktopResult -Found $true -Source "running-process" -ExecutablePath $running.ExecutablePath
  }

  try {
    $packages = @(Get-AppxPackage -Name "OpenAI.Codex" -ErrorAction Stop)
  } catch {
    try {
      $packages = @(Get-AppxPackage -ErrorAction Stop | Where-Object {
        $_.Name -like "*Codex*" -or $_.PackageFullName -like "OpenAI.Codex*"
      })
    } catch {
      $packages = @()
    }
  }

  foreach ($package in $packages) {
    if ([string]::IsNullOrWhiteSpace($package.InstallLocation)) { continue }
    $exe = Join-Path $package.InstallLocation "app\Codex.exe"
    $appId = ""
    if (-not [string]::IsNullOrWhiteSpace($package.PackageFamilyName)) {
      $appId = "$($package.PackageFamilyName)!App"
    }
    if (Test-Path -LiteralPath $exe) {
      return New-CodexDesktopResult `
        -Found $true `
        -Source "appx-package" `
        -ExecutablePath $exe `
        -AppId $appId `
        -PackageFullName $package.PackageFullName `
        -InstallLocation $package.InstallLocation
    }
    if (-not [string]::IsNullOrWhiteSpace($appId)) {
      return New-CodexDesktopResult `
        -Found $true `
        -Source "appx-package-appid" `
        -AppId $appId `
        -PackageFullName $package.PackageFullName `
        -InstallLocation $package.InstallLocation
    }
  }

  $startApp = Get-CodexStartApp
  if ($startApp -and -not [string]::IsNullOrWhiteSpace($startApp.AppID)) {
    return New-CodexDesktopResult -Found $true -Source "start-menu-appid" -AppId $startApp.AppID
  }

  $windowsApps = Join-Path $env:ProgramFiles "WindowsApps"
  try {
    $folders = @(Get-ChildItem -LiteralPath $windowsApps -Directory -Filter "OpenAI.Codex_*" -ErrorAction Stop |
      Sort-Object LastWriteTimeUtc -Descending)
    foreach ($folder in $folders) {
      $exe = Join-Path $folder.FullName "app\Codex.exe"
      if (Test-Path -LiteralPath $exe) {
        return New-CodexDesktopResult -Found $true -Source "windowsapps-scan" -ExecutablePath $exe -InstallLocation $folder.FullName
      }
    }
  } catch {
    return New-CodexDesktopResult -Source "windowsapps-scan" -ErrorMessage $_.Exception.Message
  }

  return New-CodexDesktopResult -ErrorMessage "Codex Desktop was not found. Install or open Codex Desktop once, then retry."
}

function Start-CodexDesktopApp {
  param(
    [string]$CodexAppPath = "",
    [string]$CodexAppId = "",
    [int]$WaitSeconds = 8
  )

  $initialProcess = Get-CodexDesktopProcess
  if ($initialProcess) {
    return [PSCustomObject]@{
      Found = $true
      Started = $false
      Running = $true
      Source = "already-running"
      ExecutablePath = $initialProcess.ExecutablePath
      AppId = ""
      ProcessId = $initialProcess.ProcessId
      Error = ""
    }
  }

  $app = Resolve-CodexDesktopApp -CodexAppPath $CodexAppPath -CodexAppId $CodexAppId
  if (-not $app.Found) {
    return [PSCustomObject]@{
      Found = $false
      Started = $false
      Running = $false
      Source = $app.Source
      ExecutablePath = $app.ExecutablePath
      AppId = $app.AppId
      ProcessId = $null
      Error = $app.Error
    }
  }

  $started = $false
  $errorMessage = ""
  try {
    if (-not [string]::IsNullOrWhiteSpace($app.ExecutablePath) -and (Test-Path -LiteralPath $app.ExecutablePath)) {
      Start-Process -FilePath $app.ExecutablePath | Out-Null
      $started = $true
    } elseif (-not [string]::IsNullOrWhiteSpace($app.AppId)) {
      Start-Process -FilePath "explorer.exe" -ArgumentList "shell:AppsFolder\$($app.AppId)" | Out-Null
      $started = $true
    }
  } catch {
    $errorMessage = $_.Exception.Message
    if (-not [string]::IsNullOrWhiteSpace($app.AppId)) {
      try {
        Start-Process -FilePath "explorer.exe" -ArgumentList "shell:AppsFolder\$($app.AppId)" | Out-Null
        $started = $true
        $errorMessage = ""
      } catch {
        $errorMessage = $_.Exception.Message
      }
    }
  }

  $deadline = (Get-Date).AddSeconds([Math]::Max(0, $WaitSeconds))
  $process = $null
  do {
    Start-Sleep -Milliseconds 300
    $process = Get-CodexDesktopProcess
  } while (-not $process -and (Get-Date) -lt $deadline)

  if (-not $process -and -not [string]::IsNullOrWhiteSpace($app.AppId)) {
    try {
      Start-Process -FilePath "explorer.exe" -ArgumentList "shell:AppsFolder\$($app.AppId)" | Out-Null
      $started = $true
      $deadline = (Get-Date).AddSeconds([Math]::Max(2, [Math]::Min(8, $WaitSeconds)))
      do {
        Start-Sleep -Milliseconds 300
        $process = Get-CodexDesktopProcess
      } while (-not $process -and (Get-Date) -lt $deadline)
    } catch {
      if ([string]::IsNullOrWhiteSpace($errorMessage)) {
        $errorMessage = $_.Exception.Message
      }
    }
  }

  [PSCustomObject]@{
    Found = $true
    Started = $started
    Running = [bool]$process
    Source = $app.Source
    ExecutablePath = $app.ExecutablePath
    AppId = $app.AppId
    ProcessId = if ($process) { $process.ProcessId } else { $null }
    Error = $errorMessage
  }
}
